version: '3'

services:
  uptime-kuma:
    image: .
    ports:
      - "80:3001"
    environment:
      - DB_TYPE=sqlite
      - DB_STORAGE=/app/data/uptime-kuma.db
    volumes:
      - uptime-kuma-data:/app/data
    restart: always
    healthcheck:
      disable: true

volumes:
  uptime-kuma-data: